[package]
name = "os"
version = "0.1.0"
edition = "2018"

[dependencies]

[[example]]
name = "dev"
crate-type = ["staticlib"]

[[example]]
name = "hello_world"
crate-type = ["staticlib"]

[[example]]
name = "fmt"
crate-type = ["staticlib"]

[[example]]
name = "panic"
crate-type = ["staticlib"]
